apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver-alpha-win
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newTag: "v1.2.0-gke.8"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-node-registrar-win
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.1.0"
