apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: "v1.6.1"

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-attacher
imageTag:
  name: k8s.gcr.io/sig-storage/csi-attacher
  newTag: "v2.2.1"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resizer
imageTag:
  name: k8s.gcr.io/sig-storage/csi-resizer
  newTag: "v1.0.1"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: "v2.1.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # Don't change stable image without changing pdImagePlaceholder in
  # test/k8s-integration/main.go
  newTag: "v1.2.1-gke.0"
---
